### GET index
GET https://learnink-api.vercel.app/api/

### GET alle Staples
GET https://learnink-api.vercel.app/api/staples

### POST neuen Staple
POST https://learnink-api.vercel.app/api/staples
Content-Type: application/json

{
  "name": "NOCH EINS???",
  "questions": []
}


### PUT Staple aktualisieren
PUT https://learnink-api.vercel.app/api/staples
Content-Type: application/json

{
    "name": "ES KLappt !",
    "questions": [
        {
            "text": "FRAGE !!!",
            "answers": [
                {
                    "text": "ANTWORT",
                    "isCorrect": true
                },
                {
                    "text": "ANTWORT",
                    "isCorrect": false
                },
                {
                    "text": "ANTWORT",
                    "isCorrect": false
                },
                {
                    "text": "ANTWORT",
                    "isCorrect": false
                },
                {
                    "text": "ANTWORT",
                    "isCorrect": false
                }
            ]
        }
    ],
    "_id": "69df98a39d31f50f10d1d437"
}