### GET index
GET https://learnink-api.vercel.app/api/

### GET alle Staples
GET https://learnink-api.vercel.app/api/staples

### POST neuen Staple
POST https://learnink-api.vercel.app/api/staples
Content-Type: application/json

{
  "name": "Test"
}

### POST neue Frage
POST https://learnink-api.vercel.app/api/staples/questions
Content-Type: application/json

{
  "text": "a",
  "answers": [
    {
      "id": 1,
      "text": "4",
      "isCorrect": false
    },
    {
      "id": 2,
      "text": "3",
      "isCorrect": false
    },
    {
      "id": 3,
      "text": "5",
      "isCorrect": false
    },
    {
      "id": 4,
      "text": "5",
      "isCorrect": false
    },
    {
      "id": 5,
      "text": "5",
      "isCorrect": false
    }
  ]
}